### ISSUE TITLE
Perks of approval

### ISSUE THREAD

**Issue by Twentysix26** [Cog-Creators/Applications#10]
Currently the perks that you get from being in "beta" or "approved" are very unclear.  
I think we decided that the "cog creator" role in the main server is now only for  people in the "approved" list. That's ok and I don't mind it, as it also grants access to the advanced coding channel and the bar for beta approval is a bit too low for that.

What about perks in the Cog Support channel? Who gets a role and a channel? Everyone that gets in, regardless of beta and approved? That's how it seems to be currently and I don't have strong opinions on the matter.

**Comment by palmtree5** [comment]
I'm good with it in the main server. For Cog Support, I'm of the opinion that both "Beta" and "Approved" should get the role and channel as the channels can be used for changelogs (via webhooks) and support.

**Comment by NekoTony** [comment]
Palm took the words right out of my mouth. Not literally though...

**Comment by Kowlin** [comment]
I'm fine with that.

**Comment by orels1** [comment]
Ye, I think that giving both "beta" and "approved" a dedicated channel and a role is the main purpose of Cog-Support, so users can easily find the cog's creator and contact him

**Comment by Kowlin** [comment]
seems that's settled then. I've seen great arguments both in the server and on this issue. The remaining cog creators in beta will need to get their own channels and cog creator role.
