### ISSUE TITLE
reorganize in branches

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Applications#2]
imo, should have
- [x] `master` should have only the readme and other docs
- [ ] a branch for the main tutorial
- [ ] tags for various parts of the tutorial
- [ ] tag for plain cog repo format

**Comment by Redjumpman** [comment]
- What do you want the second branch called? Would Tutorial work?
- Should they be making a PR against tutorial or master branch?
- Where do you want the tags? Like a directory at the start of the readme?
- What do you mean by plain cog repo format?

**Comment by Chovin** [comment]
* #getting-started ?
* They should PR to the branch they got the format from.
* I didn't realize you could reference tags within the read me. I'm talking about git version tags.
* Plain repo format would be the base template for all 3rd party repos. Basically how it is now but with 1 blank cog instead of the example cogs

**Comment by Redjumpman** [comment]
I'm going to be a complete noob and say that I do not understand tags at all. I have never used those. As for the branches, do you want me to create 3 branches? The first is like a landing page(Master), The second is a getting-started branch which has examples, and all the tutorial stuff. The third a template branch which is an exact template of a repo ready for submission?

**Comment by Redjumpman** [comment]
I'm thinking that those three branches above are good. Master has None the way you like it. A branch that has the example cogs and any future example cogs we want to add in. Readme in that branch can maybe explain in detail how those cogs work. A template branch which has the base template they need for their repo. I was thinking maybe a submission branch. This branch can have the pullapprove YML, and the PullRequest.md file. Too many branches? I don't want them to fork over the .yml and the extra md file.

**Comment by palmtree5** [comment]
Keep in mind that whatever branch PULL_REQUEST_TEMPLATE.md is in **MUST** be the default branch (per [this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/))

**Comment by Chovin** [comment]
YML and PR can go in master

**Comment by Chovin** [comment]
This is what I was thinking about with the tags n such

```
o--o-master
o-template---o-tut_p1--o-tut_p2---o-tut_p3---o-tut_p4--o-tutorial

or..

o---o-master
o-getting_started---o-tut_p1--o-tut_p2---o-tut_p3---o-tut_p4
```

people fork and make their repos off the getting-started branch. That is the template. If they want to go through the tutorial, they go through the following tags (just like branches) that are commented to hell and easy to follow. 
There can be a tutorial.md in master or in the wiki if wanted.
Please see this electron getting started tutorial for reference. https://medium.com/developers-writing/building-a-desktop-application-with-electron-204203eeb658#.q3wj2ychl

**Comment by Redjumpman** [comment]
You have access. Rather than me doing all this back-and-forth, just setup the tags and organize the files. Once you do that I can write the readme anyway you want.

**Comment by Chovin** [comment]
I will do so when I get the time.
_mayyybe_ Sunday. (most likely your Saturday)

I'll set up a Floobits so people can collab and bang it out.

**Comment by Chovin** [comment]
if we're going to try to make it nice and tidy like this: 
![image](https://cloud.githubusercontent.com/assets/17536161/20613584/1a972c70-b311-11e6-8665-3610c812105d.png)
we're probably going to have to edit git history. or be very careful :3

**Comment by Chovin** [comment]
does the `.pullaprove.yml`
need to be in the branch people will PR to?
can it be put into `master`?
or be ignored when people pull / clone somehow?
