### ISSUE TITLE
Review team changes

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Applications#4]
I suggest that there be a Structure/Compliance check/team and a Code check/team.
### One team to check
* conflicts between cogs
* repo format
    * file structure
    * info.json
    * #of Cogs
* citing sources and licensing
* overt maliciousness / unsavory cogs
* cogs do what they advertise
    * cogs actually work
    * other easily testable things that don't need actual reading of the code
### While the other team actually goes through the code for
* conflicts between cogs
* citing sources and licenses
* security
* code quality
etc

**Comment by palmtree5** [comment]
So as it stands now, there's three teams. @Cog-Creators/review-team @Cog-Creators/security-team and @Cog-Creators/developer

**Comment by Redjumpman** [comment]
I can change it to reflect that. I setup a developer team for just 26.

**Comment by Redjumpman** [comment]
Renamed the teams and updated the readme to reflect those changes.

For each team, it is undetermined how many people will be in each team and who those people are. Can you give me a list for both, and let me know how many approvals from each team are required to move on to the next phase?
For example, the compliance team can have 10 people, but only need 2 approvals. So any two members of that team can mark approve, and then it is sent to the next team. I can also set a require all where if on code-review it requires everyone to approve. I can also add a system where if they need 2 approvals, and one person disapproves, they now need 3 approvals.

Besides that, anything else you need in regards to teams?

**Comment by Chovin** [comment]
I like the disapproval addition thing.
Can people be in both teams? I for one may stumble accord an app and be too tired to go through code but notice something wrong in the compliance part.

As for who goes in what team... idk. We should get Kowlin/26 and us together to just hash the list out.
I'm thinking 3 approvals is good for compliance. You?

**Comment by Redjumpman** [comment]
3 approvals is enough I think. Yes people can be in multiple teams. So just need to contact 26 and kowlin and give me the list for the teams, approval number, and if anything should weighted. IE. 1 disapprove equals -1 so normal 3 yes now needs 4. Maybe you can ask in staff chat..

**Comment by palmtree5** [comment]
I like the idea of net approvals (i.e. to be added to the list, a repo needs some number of approve votes greater than the number of decline votes)
