### ISSUE TITLE
Cog Creator getting-started guide

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Applications#5]
# Possible topics for the tutorial
to put into this repo or in Red-Docs (perhaps the repo framework is the codebase that the Red-Docs tutorial points to)
if made well, this getting-started guide and group of tutorials can be our evolving knowledge-base that people can read over and quickly be able to be assimilated into the cog creating community.

### Cog-Making process
* - [ ] basic cog structure 
* - [ ] look before you leap
  * - [ ] Someone else has probably already made it. Can you PR to theirs instead?
  * - [ ] research + stay updated on conventions (lots of examples in cogs / docs)
* - [ ] testing + debug/repl + load/unload/reload
* - [x] how to publish a repo
* - [ ] I want to make a functionality change! ~~Edit files!~~ Make a new cog.

### discord.py/Red specific conventions n whatnot
* - [ ] naming conventions
* - [ ] documentation / help strings
* - [ ] commands
  * - [ ] groups
  * - [ ] name / aliases
* - [ ] ctx
* - [ ] listeners
* - [ ] settings
  * - [ ] user/channel/server/x specific
  * - [ ] defaults
  * - [ ] dataIO
* - [ ] integrating with other cogs
* - [ ] logging / printing to console
* - [ ] watcher loops (whatever they're called)
* - [ ] `__unload__`
* - [ ] timing

### Misc
* - [ ] `<#mentions>` and such
* - [ ] 2000k limit / pagify

\*`please add to this list and attach issues if needed for implementation`
\*`some of these are probably not needed in the getting-started tutorial or the knowledge-base. Discuss below!`

**Comment by Redjumpman** [comment]
These are good topics to go over. Believe it or not, I actually wrote a tutorial for some of these topics in a text file somewhere, but now I have a place to upload it. I can start working on some of these things now. 👍

**Comment by palmtree5** [comment]
With the amount of stuff in this tutorial, maybe we can turn this into like a github pages site?

**Comment by Redjumpman** [comment]
Is anyone able to do what @palmtree5 has suggested? I can organize a readme with all the content if someone can convert.

**Comment by Chovin** [comment]
I was actually thinking all of this would end up on Red-Docs at some point, replacing the current tutorials.
They would just link back here for example code

**Comment by palmtree5** [comment]
that would save us the work of trying to set up our own gh-pages site
