### ISSUE TITLE
workflow/structure for repo and tutorial

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Applications#7]
1. `master`: docs and such go here. the tutorial.md will also go here until we put it up on Red-Docs
2. `getting-started`: will be a branch that shares no history with master and with only 1 commit. the repo template. applicants will clone from and PR to this
3. tutorial tags of the format XX-topic: will be clean commits one after another, ahead of `getting-started` of example code that follows the tutorial.md
4. `develop-getting-started`: will be the branch we branch from and PR to to develop `getting-started`. once we feel sections of the tutorial are good enough for deployment, we PR them back into `getting-started` and drop a tag there. We then begin work on the next section of the tutorial. if you have content for future lessons in the tutorial, just make a branch like normal and work off of that one :thumbsup:
I believe we can merge develop back into `getting-started` cleanly via rebases or some such? maybe patches? 

please see the convos in the other issues in this epic for reference.

**Comment by Redjumpman** [comment]
Please take a look at the getting-started branch and getting-started-develop. Both have clean history, and 1 initial commit.

Not sure how to tell the user to remove all the crap from their now forked repository when they go for application. Should just have two branches(maybe one) like all other repos. 1 master and 1 develop. Maybe you can clean some stuff up from here. I think I've done most of it like you wanted.
