### ISSUE TITLE
Final Thoughts

### ISSUE THREAD

**Issue by Redjumpman** [Cog-Creators/Applications#8]
To recap those who haven't seen any of the traffic on this new application system, I've highlighted the big points.

## Phase 1:
New content creators can fork the template and start working on their cogs. When they finish they PR to this repo. Two teams will review the application for approval, before sending it off to 26 for final approval. Team 1 is compliance, and ensures the repo is setup properly. Team 2 is code-review an ensures nothing malicious is in the code, and makes sure it actually works. PR's will stay open so that a repo can be monitored and will be managed through labels. All of these features are GREEN for applications.

## Phase 2:
Create a tutorial system for making a cog. Starts from the beginning and ends with a repo that has a functioning cog. This might be done through version tags, or just a regular tutorial.

## Phase 3:
Include walk-throughs/tutorials for different aspects of Red and interaction with the discord api. These tutorials assume the user has some understanding of python. Examples would be using JSON for storing data, or how to use listeners, etc.

---
We need YOU  to throw in any comments or opinions about this new process. This isn't just a system by irdumb and I, or 26. This is a system that affects the future of all cog creators and you should be apart of it! Please leave any concerns or questions here so we  can move on with approving applications and roll out phase 1.

**Comment by Chovin** [comment]
upon some disheartening discussion:
### Deal-Breakers:

1. no visible way to PR from a non-fork:
current repos and applications would be left floating without an easy way to get back into the process.
ex. beta list repos that would like to move to approved:
2. no visible way for a repo-author to fork another author's repo 
contributions/collaboration would die out
3. PR's `allow edits from maintainers` is checked by default:
this allows people in the organization to edit their master branch (which is the one they'd be PRing with if they want to be able to use the new code review process and push "changelog" type stuff)
while we could tell them to turn it off and we could just.. not edit their stuff, this is pretty "I let myself in" uncomfortable

### this proposed change allowed for:
1. a much easier application review process:
    1. in-line code reviews (commenting on lines of code)
    2. seeing only new changes in code since last review
    3. automatically see when and what a author updates so the author doesn't have to specify what he did and then the reviewer would have to update their cog to look for the changes manually
    4. integrated review teams with point review system (if a reviewer 👎 , there needs to be more 👍 )
2. once approved, more visibility of a repo's life:
    1. users can follow the updates with the same code review system. They can see what the new updates entail and can "subscribe" (receive github notifications) to this "changelog" as well as have conversations in a timeline that makes sense in regards to the cogs' development
    2. easier, more visible contribution
    3. breaking changes and malicious content is easier for anyone in the community to point out as well as see when they are fixed
3. easier integration with documentation / cogs in the future:
    1. documentation is all in one place
    2. auto-maintained repo list n such *shrug

With the above breaking changes however, the cons outweigh the pros imo.
Would we be able to fix them? are there ways we can have some of the pros with a different solution?
please discuss below.
