### ISSUE TITLE
Adding docs.md to the cog folder as an optional

### ISSUE THREAD

**Issue by orels1** [Cog-Creators/Applications#9]
There are a lot of different kinds of cogs out there, some of them are simple enough to figure out with one !help command, but others have a lot of settings, keys and such, which can be pretty difficult for people to see and understand if all they want is for something to work.

That's why I want to propose an optional docs.md file, as well as a new field for `info.json`:

```
"DOCS": true
```

This change will require a little `downloader.py` update, to link to the docs on the first install, so you won't need to put all the stuff in the `"INSTALL_MSG"` like you do now, as well as it can let me display the rich documentation right on the cog's page at http://cogs.orels1.tips

Tell me what you think? Is it 👍 or 👎

**Comment by Chovin** [comment]
if the `docs.md` will be in each cog folder, why does there need to be an `info.json` entry?

if the `docs.md` for the specific cog may be elsewhere, why not have the `info.json` entry be this instead:
```
"DOCS": "link.to/doc.md#ThisCog"
```

**Comment by orels1** [comment]
It's easier to parse (less api calls) directly the info.json in the folder to see if there is even a reason to have an api call for the whole folder to get the docs.md
Since you'll be parsing info.json anyways
